config/routes.rb
Rails.application.routes.draw do
	root 'portfolio#index'
	get '/contact' => "portfolio#contact", as: :contact
	get	'/projects' => "portfolio#projects", as: :projects
	get	'/algorithms' => "portfolio#algorithms", as: :algorithms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
	def index
	end
	def contact
	end
	def projects
	end
	def algorithms
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Francisco's Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="background">
   <div class="container-fluid">
		<div class="center-block">
			<%= image_tag("linkenin.jpg", alt:"Francisco J Trujillo", class: "img-responsive img-circle", id:"image")%>
		</div>
		<h1 class="text-center">Francisco J. Trujillo</h1>
		<h2 class="text-center">Full Stack Developer</h2>
		<div class="row partials">
			<div class="col-xs-12">
				<%= yield %>
			</div>
    	</div>
    </div>
  </body>
</html>

app/views/portfolio/algorithms.html.erb
<ul class="nav nav-tabs nav-justified">
	<li role="presentation"><%=link_to("Home", root_path)%></li>
	<li role="presentation"><%= link_to("Projects",projects_path)%></li>
	<li role="presentation" class="active"><%= link_to("Algorithms",algorithms_path)%></li>
	<li role="presentation"><%= link_to("Contact information",contact_path)%></li>
</ul>

<div class="row">
	<%= image_tag("Under_Construction.png", alt:"Under Construction", class: "img-responsive center-block construction")%>
	</div>

app/views/portfolio/contact.html.erb
<ul class="nav nav-tabs nav-justified">
	<li role="presentation"><%=link_to("Home", root_path)%></li>
	<li role="presentation"><%= link_to("Projects",projects_path)%></li>
	<li role="presentation"><%= link_to("Algorithms",algorithms_path)%></li>
	<li role="presentation" class="active"><%= link_to("Contact information",contact_path)%></li>
</ul>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-4">
		<%= image_tag("smartphonel.png", alt:"Phone:", class: "img-responsive block-line size")%>
		<h3 class="text-center font">+1 (312) 804-5163</h3>
	</div>
	<div class="col-md-4">
		<%= image_tag("email.png", alt:"Email", class: "img-responsive block-line size")%>
		<h3 class="text-center"><%=mail_to("francisco@papelex.net","Em@il", class: "font" )%></h3>
	</div>
</div>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-4">
		<%= image_tag("In-Black-66px-TM.png", alt:"LinkedIn Profile", class: "img-responsive block-line size")%>
		<h3 class="text-center"><%=link_to("Profile", "http://www.linkedin.com/in/francisco-j-trujillo", class: "font" ) %></h3>
	</div>
	<div class="col-md-4">	
		<%= image_tag("GitHub-Mark-64px.png", alt:"GitHub Repository", class: "img-responsive block-line size")%>
		<h3 class="text-center"><%=link_to("Repository", "http://www.github.com/franciscojt", class: "font") %></h3>
	</div>
	<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-md-4 codewar">
		<embed src="https://www.codewars.com/users/franciscojt/badges/micro" type="image/svg+xml" id="codewars"/>
		<h3 class="text-center"><%=link_to("Codewars", "http://www.codewars.com", class: "font") %></h3>
	</div>
	</div>
</div>

app/views/portfolio/index.html.erb
<ul class="nav nav-tabs nav-justified">
	<li role="presentation" class="active"><%=link_to("Home", root_path)%></li>
	<li role="presentation"><%= link_to("Projects",projects_path)%></li>
	<li role="presentation"><%= link_to("Algorithms",algorithms_path)%></li>
	<li role="presentation"><%= link_to("Contact information",contact_path)%></li>
</ul>
<div class="content">
	<h3>A summary about me:</h3>
	<p>Ever since I can remember, I’ve been enamored with computers. When I was a child, I used to play with my father’s computer and learn what this thing called “technology” was.  While pursuing my bachelors in Biology, the love of technology was always present, however, I decided to keep tinkering around with computers only as a hobby.</p>

	<p>While my career continued to grow, I learned about various types of software and how computers continued to evolve…this only ignited my passion even more which led me to Coding Dojo. It was at the Coding Dojo Bootcamp where I learned 3 stacks and several languages such as: JavaScript, Ruby, Python, HTML, and CSS. </p>

	<p>Now, not only am I still extremely passionate about Programming, I’m now equipped to work on projects and pursue my career in Software Development as a Full Stack Developer. </p>

	<p>I’m happy I didn’t give up on my dream… and to think, all of this started with an old computer and a dream…</p>

	<p>If you would like to learn more about my work or contact me. Please go to the <%= link_to("Projects tab",projects_path)%> or <%= link_to("Contact information tab",contact_path)%>.</p>
	<h3>Technologies</h3>
	<p>I am a person that is always eager to learn new technologies, langauges, and frameworks as they become available. Please see below:</p>
	<ul class="list-unstyled">
		<li><span class="tech">Language:</span> Python, Ruby, JavaScript</li>
		<li><span class="tech">Front End:</span> HTML5, CCS3, Bootstrap, AngulaJS, JQuery</li>
		<li><span class="tech">Back End:</span> Django, Pylot, Rails, AngularJS, NodeJS</li>
		<li><span class="tech">Other Technologies:</span> Algorithms, Git, GitHub, Deployments</li>
	</ul>
</div>

app/views/portfolio/projects.html.erb
<ul class="nav nav-tabs nav-justified">
	<li role="presentation"><%=link_to("Home", root_path)%></li>
	<li role="presentation" class="active"><%= link_to("Projects",projects_path)%></li>
	<li role="presentation"><%= link_to("Algorithms",algorithms_path)%></li>
	<li role="presentation"><%= link_to("Contact information",contact_path)%></li>
</ul>

<div class="row project">
	<div class="col-xs-12">
		<h4>Albion Environmental (<a href="https://github.com/franciscojt/albion">Source Code</a>)</h4>
		<ul>
			<li>Created a web app for Albion Environmental which allows delivery of lab reports and data to private and government clients</li>
			<li>App developed using Ruby on Rails, CarrierWave, and MailForm</li>
			<li>Coordinated with two colleagues and a company liaison to deliver the product that met security and performance expectations</li>
		</ul>
		
	</div>

</div>